---
- name: Install Nginx
  hosts: manage-node
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
