name: 'Creation Nginx'
on:
  workflow_dispatch:
    inputs:
      Run:
        description: 'Wanna run'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Private SSH key
        run: |
          mkdir -p ~/.ssh/
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini nginx.yaml
