name: 'Creation Nginx'
on:
  workflow_dispatch:
    inputs:
      Run:
        description: 'Wanna run'
        required: true
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Private SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/ /\\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install ansible

      - name: Collect EC2 host key
        run: |
          ansible -i inventory.ini manage-node -m raw -a "ssh-keyscan -H 13.127.96.165" | sed 's/ /\\n/g' > ~/.ssh/known_hosts
        env:
          EC2_INSTANCE_IP: 13.127.96.165
          
      
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini creationnginx.yaml

