name: 'Creation Nginx'
on:
  workflow_dispatch:
    inputs:
      Run:
        description: 'Wanna run'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa 13.127.96.165 >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini nginx.yaml

