name: Deploy Nginx on EC2

on:
  workflow_dispatch:
    inputs:
      Run it:
        description: 'Wanna run'
        required: true
        
jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pip
        run: python -m ensurepip --default-pip

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip3 install ansible

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sudo cp ~/.ssh/id_rsa /etc/ansible/hosts
          sudo chown root:root /etc/ansible/hosts
          sudo chmod 600 /etc/ansible/hosts

      - name: Display SSH Key
        run: cat /etc/ansible/hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i /etc/ansible/hosts -e "ansible_ssh_private_key_file=/etc/ansible/hosts" -u ubuntu -b creationnginx.yaml
        env:
          AWS_REGION: ap-south-1  # Replace with your AWS region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

