name: Install nginx

on:
  # push:
  #   branches:
  #    - master
  workflow_dispatch:
    inputs:
      Run:
        description: 'Wanna run'
        required: true

jobs:
  install-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Private SSH key
      run: |
        mkdir -p /home/runner/.ssh/
        touch /home/runner/.ssh/id_rsa
        echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
        chmod 700 /home/runner/.ssh/id_rsa
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install python3-pip
        sudo apt install ansible
        ansible --version

    - name: Run Playbook
      run: ansible-playbook -i inventory.ini nginx.yaml
