name: Undeploy Nginx on EC2

on:
  workflow_dispatch:
    inputs:
      Run it:
        description: 'Wanna run'
        required: true
        
jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo apt install ansible
          
      - name: Set up SSH Key
        run: |
          mkdir -p /home/runner/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 400 /home/runner/.ssh/id_rsa
        shell: bash

   
      - name: Add EC2 Host Key
        run: ssh-keyscan -H -t rsa 3.110.134.38 >> ~/.ssh/known_hosts

      - name: Uninstalling Nginx
        run: ansible-playbook -i inventory.ini UninstallNginx.yaml
        
